package enums.schedulers;

public enum SchedulerType {
	SINGLE_THREAD_SCHEDULER,
	FIXED_SCHEDULER,
	SEDA_SCHEDULER,
	SYSTEM_FIXED_SCHEDULER,
	SYSTEM_CACHED_POOL_SCHEDULER,
	FORK_JOIN_POOL_SCHEDULER;
}
